name: Docker Test

description: Test the published Docker image by running the container and verifying functionality.

runs:
  using: "composite"
  steps:
    # Run the container in detached mode
    - name: Run Docker container
      shell: bash 
      run: |
        docker run -d --name test-container -p 8082:8082 -p 3333:3333 ${{ inputs.image }}

    # Wait for the container to initialize (adjust sleep time as needed)
    - name: Wait for container to be ready
      shell: bash
      run: |
        sleep 10 # Adjust this to match your container's startup time
        docker logs test-container

    # Set up the Go environment
    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    # (Optional) Run Go tests (customize this step if needed)
    # Uncomment this if you have tests to run
    # - name: Run tests
    #   run: |
    #     # Ensure test files are present in ./tests or adjust path accordingly
    #     go test ./tests -v

    # Stop and clean up the container after tests
    - name: Stop and clean up container
      shell: bash
      run: docker rm -f test-container

# Input variables
inputs:
  image:
    description: "The Docker image to test"
    required: true