name: "Upload Release"
description: "Upload release assets to GitHub release"
inputs:
  github-token:
    description: "GitHub token for authentication"
    required: true
  release-id:
    description: "ID of the release to upload assets to"
    required: true
  path:
    description: "Path to the artifact directory containing files to upload"
    required: true

runs:
  using: "node20"
  main: "index.js"
