name: CI-CD
# Intended workflow and validation:
# 0. Develop in feature branches and PR to `dev` branch for internal validation,
#    - Once validated in dev, PR/PUSH to `test` - this will create OS Test Release, Test Container image and deploy to DEV environment
#    - Once validated in test, PR/PUSH to `main` - this will create Latest Release, Latest container image and deploy to LMR environment
#    - Once validated in main, PR/PUSH to origin main on the MorpheusAI repo (no builds/triggers will happen here, only code updates)
# 1. PUSH to cicd/* will (special branches that will enable push testing of cicd changes)
#    - Generate a new tag
#    - Build and test the Docker image
#    - Build and test the macOS-arm64 image
# 2. PR to dev will
#   - Generate a new tag
#   - Build and test the Docker image
# 2 PUSH to dev will
#   - Generate a new tag
#   - Build and test the Docker image
#   - Build and test the macOS-arm64 image
# 3. PR to test or main will
#   - Generate a new tag
#   - Build and test the Docker image
# 4. PUSH to test or main will
#   - Generate a new tag
#   - Build and test the Docker image
#   - Build all 4 OS Versions
#   - Create a release and upload the artifacts
#   - Build and push the Docker image to GitHub Container Registry
#   - Deploy to GitLab

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: "Create updated Morpheus-Lumerin-Node release"
        required: true
        type: boolean
      build_all_os:
        description: "Build all OS & container image"
        required: true
        type: boolean

  push:
    branches:
      - main
      - test
      - dev
      - cicd/*

    paths: [".github/workflows/build.yml", "ui-desktop/**"]

  pull_request:
    types: [opened, reopened, synchronize]
    paths: [".github/workflows/build.yml", "ui-desktop/**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  LLAMA_URL: https://github.com/ggml-org/llama.cpp/releases/download
  LLAMA_RELEASE: b4406
  LLAMA_FILEBASE: llama-b4406-bin
  MODEL_URL: https://huggingface.co
  MODEL_OWNER: TheBloke
  MODEL_REPO: TinyLlama-1.1B-Chat-v1.0-GGUF
  MODEL_NAME: tinyllama-1.1b-chat-v1.0.Q2_K.gguf
  KUBO_URL: https://github.com/ipfs/kubo/releases/download/v0.30.0
  KUBO_FILE_LINUX: kubo_v0.30.0_linux-amd64.tar.gz
  KUBO_FILE_MAC: kubo_v0.30.0_darwin-amd64.tar.gz
  KUBO_FILE_WIN: kubo_v0.30.0_windows-amd64.zip
  #tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf

jobs:
  Generate-Tag:
    runs-on: ubuntu-latest
    name: Generate Tag Name
    outputs:
      tag_name: ${{ steps.gen_tag_name.outputs.tag_name }}
      vtag: ${{ steps.gen_tag_name.outputs.vtag }}
      vfull: ${{ steps.gen_tag_name.outputs.vfull }}
      image_name: ${{ steps.gen_tag_name.outputs.image_name }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Determine tag name
        id: gen_tag_name
        shell: bash
        run: |
          IMAGE_NAME="ghcr.io/lumerin-protocol/morpheus-lumerin-node"
          VMAJ_NEW=2
          VMIN_NEW=0
          VPAT_NEW=0
          set +o pipefail
          VLAST=$(git describe --tags --abbrev=0 --match='v[1-9]*' refs/remotes/origin/main 2>/dev/null | cut -c2-)

          if [ -n "$VLAST" ]; then
              eval $(echo "$VLAST" | awk -F '.' '{print "VMAJ="$1" VMIN="$2" VPAT="$3}')
          else
              VMAJ=0
              VMIN=0
              VPAT=0
          fi

          if [ "$GITHUB_REF_NAME" = "main" ]; then
              if [ "$VMAJ_NEW" -gt "$VMAJ" ]; then
                  VMAJ=$VMAJ_NEW
                  VMIN=$VMIN_NEW
                  VPAT=$VPAT_NEW
              else
                  VMIN=$((VMIN+1))
                  VPAT=0
              fi
              VFULL=${VMAJ}.${VMIN}.${VPAT}
              VTAG=v$VFULL
          else
              MB=$(git merge-base refs/remotes/origin/main HEAD)
              VPAT=$(git rev-list --count --no-merges ${MB}..HEAD)
              VFULL=${VMAJ}.${VMIN}.${VPAT}
              RNAME=${GITHUB_REF_NAME##*/}
              [ "$GITHUB_EVENT_NAME" = "pull_request" ] && RNAME=pr${GITHUB_REF_NAME%/merge}
              VTAG=v${VFULL}-${RNAME}
          fi

          # Output variables for use in subsequent jobs environment
          echo "::set-output name=tag_name::${VTAG}"
          echo "::set-output name=vtag::${VTAG}"
          echo "::set-output name=vfull::${VFULL}"
          echo "::set-output name=image_name::${IMAGE_NAME}"
          echo "✅ New Build Tag: $VTAG" >> $GITHUB_STEP_SUMMARY
          echo "✅ Docker Image: ${IMAGE_NAME}:${VTAG}" >> $GITHUB_STEP_SUMMARY
          echo "❌ Old Major Tag: $VLAST"  >> $GITHUB_STEP_SUMMARY

  macOS-14-arm64:
    name: Build macOS-arm64 Image
    if: |
      github.repository != 'MorpheusAIs/Morpheus-Lumerin-Node' &&
      (
        (github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/cicd/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' || github.ref == 'refs/heads/dev')) ||
        (github.event_name == 'workflow_dispatch' && (github.event.inputs.create_release == 'true' || github.event.inputs.build_all_os == 'true')) 
      )
    runs-on: macos-14
    needs: Generate-Tag
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: ui-desktop/yarn.lock

      - name: Install dependencies
        run: |
          cd ./ui-desktop
          brew install python-setuptools
          yarn install --network-timeout 600000

      - name: Copy Environment Files
        uses: ./.github/actions/copy_env_files

      - name: Build
        id: build
        run: |
          FULLTAG=${{ needs.Generate-Tag.outputs.vfull }}
          cd ./ui-desktop
          echo "Injecting version $FULLTAG into package.json"
          sed -i "" "s/\"version\": \".*\"/\"version\": \"$FULLTAG\"/" package.json
          cat package.json | grep '"version"'  # Optional: Verify the change
          yarn build:mac

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./ui-desktop/dist/morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-arm64-mac.dmg
          name: morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-arm64-mac.dmg

  Ubuntu-22-x64:
    name: Build Ubuntu Image
    if: |
      github.repository != 'MorpheusAIs/Morpheus-Lumerin-Node' &&
      false &&
      (
        (github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/cicd/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' || github.ref == 'refs/heads/dev')) ||
        (github.event_name == 'workflow_dispatch' && (github.event.inputs.create_release == 'true' || github.event.inputs.build_all_os == 'true')) 
      )
    runs-on: ubuntu-22.04
    needs: Generate-Tag
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: ui-desktop/yarn.lock

      - name: Install dependencies
        run: |
          cd ./ui-desktop
          yarn install --network-timeout 600000

      - name: Copy Environment Files
        uses: ./.github/actions/copy_env_files

      - name: Build
        id: build
        run: |
          FULLTAG=${{ needs.Generate-Tag.outputs.vfull }}
          cd ./ui-desktop
          echo "Injecting version $FULLTAG into package.json"
          sed -i "s/\"version\": \".*\"/\"version\": \"$FULLTAG\"/" package.json
          cat package.json | grep '"version"'  # Optional: Verify the change
          yarn build:linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./ui-desktop/dist/morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-x86_64-linux.AppImage
          name: morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-x86_64-linux.AppImage

  macOS-13-x64:
    name: Build macOS-x64 Image
    if: |
      github.repository != 'MorpheusAIs/Morpheus-Lumerin-Node' &&
      false &&
      (
        (github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/cicd/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' || github.ref == 'refs/heads/dev')) ||
        (github.event_name == 'workflow_dispatch' && (github.event.inputs.create_release == 'true' || github.event.inputs.build_all_os == 'true')) 
      )
    runs-on: macos-13
    needs: Generate-Tag
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: ui-desktop/yarn.lock

      - name: Install dependencies
        run: |
          cd ./ui-desktop
          python3 -m pip install setuptools
          yarn install --network-timeout 600000

      - name: Copy Environment Files
        uses: ./.github/actions/copy_env_files

      - name: Build
        id: build
        run: |
          FULLTAG=${{ needs.Generate-Tag.outputs.vfull }}
          cd ./ui-desktop
          echo "Injecting version $FULLTAG into package.json"
          sed -i "" "s/\"version\": \".*\"/\"version\": \"$FULLTAG\"/" package.json
          cat package.json | grep '"version"'  # Optional: Verify the change
          yarn build:mac

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./ui-desktop/dist/morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-x64-mac.dmg
          name: morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-x64-mac.dmg

  Windows-avx2-x64:
    name: Build Windows Image
    if: |
      false &&
      github.repository != 'MorpheusAIs/Morpheus-Lumerin-Node' &&
      (
        (github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/cicd') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' || github.ref == 'refs/heads/dev')) ||
        (github.event_name == 'workflow_dispatch' && (github.event.inputs.create_release == 'true' || github.event.inputs.build_all_os == 'true')) 
      )
    runs-on: windows-latest
    needs: Generate-Tag
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: ui-desktop/yarn.lock

      - name: Install wget and sed
        run: |
          choco install wget --no-progress
          choco install sed --no-progress

      - name: Install dependencies
        run: |
          cd ./ui-desktop
          yarn install --network-timeout 600000

      - name: Copy Environment Files
        uses: ./.github/actions/copy_env_files

      - name: Build
        id: build
        run: |
          FULLTAG=${{ needs.Generate-Tag.outputs.vfull }}       
          cd ./ui-desktop
          echo "Injecting version $FULLTAG into package.json"
          sed -i "s/\"version\": \".*\"/\"version\": \"$FULLTAG\"/" package.json
          cat package.json | grep '"version"'  # Optional: Verify the change
          yarn build:win

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./ui-desktop/dist/morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-x64-win.exe
          name: morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-x64-win.exe

  Release:
    name: Create Release
    if: |
      github.repository != 'MorpheusAIs/Morpheus-Lumerin-Node' &&
      (
        (github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/cicd/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' || github.ref == 'refs/heads/dev')) ||
        (github.event_name == 'workflow_dispatch' && github.event.inputs.create_release == 'true')
      )
    needs:
      - Generate-Tag
      # - Ubuntu-22-x64
      # - macOS-13-x64
      - macOS-14-arm64
      # - Windows-avx2-x64
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Download artifacts
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          path: ./artifact
          merge-multiple: true

      - name: LIST FILES
        id: list_files
        run: |
          ls -R ./artifact

      - name: Create release
        id: create_release
        uses: anzz1/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.Generate-Tag.outputs.tag_name }}
          prerelease: ${{ github.ref != 'refs/heads/main' }}

      - name: Upload release
        id: upload_release
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const release_id = '${{ steps.create_release.outputs.id }}';
            for (let file of await fs.readdirSync('./artifact')) {
              console.log('uploading file', file);
              if (fs.statSync(`./artifact/${file}`).isDirectory()) {
                console.log('is directory with contents: ', await fs.readdirSync(`./artifact/${file}`));
                continue;
              }
              await github.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release_id,
                name: file,
                data: await fs.readFileSync(`./artifact/${file}`)
              });
            }

  GitLab-Deploy:
    name: Deploy to GitLab
    if: |
      github.repository != 'MorpheusAIs/Morpheus-Lumerin-Node' &&
      (
        (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test'))
      )
    needs:
      - Generate-Tag
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: Trigger GitLab Pipeline
        run: |
          BUILDTAG=${{ needs.Generate-Tag.outputs.tag_name }}
          FULLTAG=${{ needs.Generate-Tag.outputs.vfull }}       
          echo "Triggering GitLab Deploy for branch ${{ github.ref_name }} with tag $BUILDTAG"
          # Determine branch
          if [ "${{ github.ref_name }}" == "test" ]; then
            GITLABBRANCH="dev"
          elif [ "${{ github.ref_name }}" == "main" ]; then
            GITLABBRANCH="main"
          else
            echo "❌ This branch is not configured to trigger GitLab pipelines."
            exit 1
          fi
          echo "✅ Sending Request to GitLab branch: $GITLABBRANCH"
          response=$(curl --silent \
            --request POST \
            --url "${{ secrets.GITLAB_TRIGGER_URL }}" \
            --form "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
            --form "ref=$GITLABBRANCH" \
            --form "variables[SOURCE_REPO]=${{ github.repository }}" \
            --form "variables[SOURCE_BRANCH]=${{ github.ref_name }}" \
            --form "variables[GITHUB_VFULL]=$FULLTAG" \
            --form "variables[GITHUB_TAG]=$BUILDTAG")

          # Parse JSON response using jq
          gitlab_status=$(echo "$response" | jq -r '.status // "unknown"')
          gitlab_web_url=$(echo "$response" | jq -r '.web_url // "N/A"')

          # Log the response
          echo "GitLab Response: $response"

          # Validate the status field
          if [[ "$gitlab_status" =~ ^(created|preparing|success|running|scheduled)$ ]]; then
            echo "✅ GitLab pipeline triggered successfully! Status: $gitlab_status"
            echo "Pipeline details: $gitlab_web_url"
          else
            echo "❌ GitLab pipeline FAILED. Invalid status: $gitlab_status"
            echo "Pipeline details: $gitlab_web_url"
            exit 1
          fi
